//
// Created by ASUS on 6/7/2024.
//

#ifndef RUBIKSCUBESOLVEREXPLAIN_GENERICRUBIKSCUBE_H
#define RUBIKSCUBESOLVEREXPLAIN_GENERICRUBIKSCUBE_H


class GenericRubiksCube {
SubhaOrku;
};


#endif //RUBIKSCUBESOLVEREXPLAIN_GENERICRUBIKSCUBE_H
