//
// Created by ASUS on 6/15/2024.
//

#ifndef RUBIKSCUBESOLVEREXPLAIN_IDASTARSOLVER_H
#define RUBIKSCUBESOLVEREXPLAIN_IDASTARSOLVER_H


class IDAstarSolver {

};


#endif //RUBIKSCUBESOLVEREXPLAIN_IDASTARSOLVER_H
